baseURL = "https://www.methos.nl"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Methos"
theme = "methos"
themesdir = "themes"
pygmentsCodeFences = true
pygmentsStyle = "monokai"

defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

disableKinds = ["taxonomy", "taxonomyTerm", "category", "RSS"]

[params]
ordersectionsby = "weight" # ordersectionsby = "title"
color_main = "#737373"
color_second = "#1090c8"
disableSearch = false # default is false
disableNavChevron = true  # set true to hide next/prev chevron, default is false
menushortcutsnewtab = false # set true to open shortcuts links to a new tab/window

editWithNetlifyCMSURL = "admin/#/collections/pages/entries/"
enableGitInfo = true

googleMapsAPIKey = "AIzaSyAqeOqJSJZ-LaUIVRljsnwwCMAYYJhiMiE"

[mediaTypes]
  [mediaTypes."application/netlifyconfig"]
    suffixes = ["yml"]

[outputFormats]
[outputFormats.netlifyyaml]
mediaType = "application/netlifyconfig"
isPlainText = true
isHTML = false
notAlternative = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe = true

# Code highlight configuration
[markup.highlight]
codeFences = true
guessSyntax = true
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 2

#
# top menu shotcuts
#
#[[menu.shortcuts]]
#name = "ScriptPortal"
#identifier = "sp"
#url = "https://www.scriptportal.com"
#weight = 10

#[[menu.shortcuts]]
#name = "LicenseServer"
#identifier = "licsrv"
#url = "https://www.licsrv.com"
#weight = 20